include_guard(GLOBAL)
include(FetchContent)

# Source-only downloads never configure another component's native project.
function(mmfg_source name variable repository revision required out)
    if(NOT DEFINED ${variable})
        set(${variable} "$ENV{${variable}}" CACHE PATH "Local ${name} sources; empty fetches a pinned revision")
    endif()
    if(${variable})
        get_filename_component(source "${${variable}}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    else()
        FetchContent_Declare(mmfg_${name} GIT_REPOSITORY "${repository}" GIT_TAG "${revision}"
            GIT_SUBMODULES "" GIT_SUBMODULES_RECURSE FALSE SOURCE_SUBDIR mmfg-source-only)
        FetchContent_MakeAvailable(mmfg_${name})
        set(source "${mmfg_${name}_SOURCE_DIR}")
    endif()
    foreach(file IN LISTS required)
        if(NOT EXISTS "${source}/${file}" OR IS_DIRECTORY "${source}/${file}")
            message(FATAL_ERROR "${variable} is missing ${file}: ${source}")
        endif()
    endforeach()
    message(STATUS "${variable}: ${source}")
    set(${out} "${source}" PARENT_SCOPE)
endfunction()

function(mmfg_capstone_headers)
    get_filename_component(MMFG_METAMOD_ROOT "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
    if(TARGET Capstone::Headers)
        return()
    endif()
    if(NOT DEFINED CAPSTONE_SOURCE_PATH AND NOT "$ENV{CAPSTONE_SOURCE_PATH}" STREQUAL "")
        set(CAPSTONE_SOURCE_PATH "$ENV{CAPSTONE_SOURCE_PATH}")
    endif()
    if(NOT CAPSTONE_SOURCE_PATH AND EXISTS "${MMFG_METAMOD_ROOT}/thirdparty/capstone_fork/include/capstone/capstone.h")
        set(CAPSTONE_SOURCE_PATH "${MMFG_METAMOD_ROOT}/thirdparty/capstone_fork")
    endif()
    mmfg_source(capstone CAPSTONE_SOURCE_PATH https://github.com/hzqst/capstone.git
        6d71a27ad3d7da91c20169401c1d659207f8704d "CMakeLists.txt;include/capstone/capstone.h" source)
    add_library(mmfg_capstone_headers INTERFACE)
    add_library(Capstone::Headers ALIAS mmfg_capstone_headers)
    target_include_directories(mmfg_capstone_headers INTERFACE "${source}/include")
    set_property(TARGET mmfg_capstone_headers PROPERTY MMFG_SOURCE "${source}")
endfunction()

function(mmfg_capstone_library)
    mmfg_capstone_headers()
    if(NOT TARGET capstone-static)
        get_target_property(source mmfg_capstone_headers MMFG_SOURCE)
        set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
        set(CAPSTONE_ARCHITECTURE_DEFAULT OFF)
        foreach(architecture ARM ARM64 M68K MIPS PPC SPARC SYSZ XCORE TMS320C64X M680X EVM)
            set(CAPSTONE_${architecture}_SUPPORT OFF)
        endforeach()
        set(CAPSTONE_X86_SUPPORT ON)
        set(CAPSTONE_BUILD_STATIC ON)
        set(CAPSTONE_BUILD_STATIC_RUNTIME ON)
        set(CAPSTONE_USE_DEFAULT_ALLOC ON)
        foreach(option BUILD_SHARED BUILD_TESTS BUILD_CSTOOL INSTALL BUILD_DIET X86_REDUCE)
            set(CAPSTONE_${option} OFF)
        endforeach()
        add_subdirectory("${source}" "${CMAKE_BINARY_DIR}/vendor/capstone" EXCLUDE_FROM_ALL)
        set_target_properties(capstone-static PROPERTIES POSITION_INDEPENDENT_CODE ON)
    endif()
endfunction()

function(mmfg_procmap_library)
    get_filename_component(MMFG_METAMOD_ROOT "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
    if(TARGET procmap)
        return()
    endif()
    if(NOT DEFINED PROCMAP_SOURCE_PATH AND NOT "$ENV{PROCMAP_SOURCE_PATH}" STREQUAL "")
        set(PROCMAP_SOURCE_PATH "$ENV{PROCMAP_SOURCE_PATH}")
    endif()
    if(NOT PROCMAP_SOURCE_PATH AND EXISTS "${MMFG_METAMOD_ROOT}/thirdparty/procmap_fork/CMakeLists.txt")
        set(PROCMAP_SOURCE_PATH "${MMFG_METAMOD_ROOT}/thirdparty/procmap_fork")
    endif()
    mmfg_source(procmap PROCMAP_SOURCE_PATH https://github.com/hzqst/procmap.git
        405a9b9ab23c7d2aa6602509d4d0bca34c6aa527 "CMakeLists.txt;include/procmap/MemoryMap.hpp" source)
    set(BUILD_TESTING OFF)
    set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
    add_subdirectory("${source}" "${CMAKE_BINARY_DIR}/vendor/procmap" EXCLUDE_FROM_ALL)
endfunction()

function(mmfg_angelscript_headers)
    if(TARGET AngelScript::Headers)
        return()
    endif()
    include("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/Revisions.cmake")
    mmfg_source(angelscript ANGELSCRIPT_SOURCE_PATH https://github.com/metamod-fallguys/angelscript-sdk.git
        "${MMFG_ANGELSCRIPT_REVISION}" "angelscript/include/angelscript.h" source)
    add_library(mmfg_angelscript_headers INTERFACE)
    add_library(AngelScript::Headers ALIAS mmfg_angelscript_headers)
    target_include_directories(mmfg_angelscript_headers INTERFACE "${source}/angelscript/include")
endfunction()

function(mmfg_bullet_library)
    if(TARGET BulletDynamics)
        return()
    endif()
    mmfg_source(bullet BULLET3_SOURCE_PATH https://github.com/hzqst/bullet3.git
        1217225ca0ad39a7982513d47ca7364ed16f0043 "CMakeLists.txt;src/btBulletDynamicsCommon.h" source)
    set(BUILD_SHARED_LIBS OFF)
    set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
    set(BUILD_BULLET3 ON)
    foreach(option BULLET2_DEMOS BULLET_ROBOTICS_EXTRA BULLET_ROBOTICS_GUI_EXTRA CLSOCKET
        CONVEX_DECOMPOSITION_EXTRA CPU_DEMO NET EXTRAS GIMPACTUTILS_EXTRA HACD_EXTRA
        INVERSE_DYNAMIC_EXTRA OBJ2SDF_EXTRA OPENGL3_DEMOS PYBULLET SERIALIZE_EXTRA UNIT_TESTS)
        set(BUILD_${option} OFF)
    endforeach()
    foreach(option MSVC_SSE2 MSVC_SSE MSVC_AVX MSVC_AVX2 GLUT GRAPHICAL_BENCHMARK)
        set(USE_${option} OFF)
    endforeach()
    set(B3_USE_CLEW OFF)
    set(INSTALL_LIBS OFF)
    set(CMAKE_POSITION_INDEPENDENT_CODE ON)
    add_subdirectory("${source}" "${CMAKE_BINARY_DIR}/vendor/bullet" EXCLUDE_FROM_ALL)
    add_library(mmfg_bullet INTERFACE)
    add_library(Bullet::Libraries ALIAS mmfg_bullet)
    target_include_directories(mmfg_bullet INTERFACE "${source}/src")
    target_link_libraries(mmfg_bullet INTERFACE Bullet3Dynamics Bullet3Collision Bullet3Common
        Bullet3Geometry BulletSoftBody BulletDynamics BulletCollision LinearMath)
endfunction()
