name: build
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  native:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-24.04]
        config: [Debug, Release]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib
      - if: runner.os == 'Windows'
        run: cmake -S . -B build/native -A Win32
      - if: runner.os == 'Linux'
        run: cmake -S . -B build/native -DCMAKE_BUILD_TYPE=${{ matrix.config }}
      - run: cmake --build build/native --config ${{ matrix.config }} --parallel 4
      - run: cmake --install build/native --config ${{ matrix.config }} --prefix install
